# Reimbursement form
- expense_purpose: Drinks for social night
- person:
    - name: Joel Ostblom
    - github_user: @joelostblom
    - proxy:
        - name: Luke Johnston 
        - github_user: @lwjohnst86
- receipts:
    - item:
        - purchase_date: 2017-04-26
        - description: Drinks from GSU Pub for social night
        - keyword: Drinks
        - cost: 44
        - receipt_file: 2017-04-26-Drinks-GSUPub-Joel.jpg
        - note: 5 dollar tip
- pr_num: 145
