# Reimbursement form
- expense_purpose: Coffee and Tea for SWC workshop on Feb 3-4, 2017
- person:
    - name: Innis Cafe (catering company)
    - proxy:
        - name: Luke Johnston
        - github_user: @lwjohnst86
- receipts:
    - item:
        - purchase_date: 2017-02-03
        - description: Coffee and tea catering
        - keyword: For SWC participants
        - cost: 409.63
        - receipt_file: 2017-02-03-Invoice-InnisCafe.pdf
- pr_num: 77
